[build-system]
requires = ["scikit-build-core>=0.8", "pybind11"]
build-backend = "scikit_build_core.build"

[project]
name = "openSoT"
version = "5.0.0"
description = "openSoT python"
requires-python = ">=3.10"
dependencies = [
    "numpy",
]

[project.optional-dependencies]
viser = ["viser<=1.0.26", "yourdfpy", "h5py", "scipy"]

[tool.scikit-build]
cmake.version = ">=3.20"
build-dir = "build/{wheel_tag}"
cmake.build-type = "Release"
cmake.define = { OPENSOT_COMPILE_EXAMPLES = "OFF", OPENSOT_COMPILE_TESTS = "OFF" }
wheel.packages = []
