export LD_LIBRARY_PATH=/home/forest_ws/install/lib:$LD_LIBRARY_PATH
export CMAKE_PREFIX_PATH=/home/forest_ws/install:$CMAKE_PREFIX_PATH
export PATH=/home/forest_ws/install/bin:$PATH
export GAZEBO_PLUGIN_PATH=/home/forest_ws/install/lib:$GAZEBO_PLUGIN_PATH
export PYTHONPATH=/home/forest_ws/install/lib/python3.12/site-packages:/home/forest_ws/install/lib/python3/dist-packages:$PYTHONPATH
#export ROS_PACKAGE_PATH=/home/forest_ws/ros_src:/home/forest_ws/install/share:/home/forest_ws/install/lib:$ROS_PACKAGE_PATH
#export AMENT_PREFIX_PATH=/home/forest_ws/install:$AMENT_PREFIX_PATH
export PKG_CONFIG_PATH=/home/forest_ws/install/lib/pkgconfig:$PKG_CONFIG_PATH
# export HHCM_FOREST_PATH=/home/forest_ws:$HHCM_FOREST_PATH
