name: full build and test

on:
  workflow_dispatch:
  push:
    branches:
      - 5.0_devel

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/hucebot/opensot/opensot-test:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Build
        shell: bash
        run: |
            mkdir build && cd build
            cmake -DCMAKE_BUILD_TYPE:STRING=Release \
                -DOPENSOT_COMPILE_TESTS=On \
                ..
            make -j$(nproc)
            cmake --install .

      - name: Test c++
        shell: bash
        run: |
            cd build/tests
            ctest --output-on-failure

      - name: Test python
        shell: bash
        run: |
            cd ./bindings/python
            pytest .
